### ISSUE TITLE
staff.py no longer working

### ISSUE THREAD

**Issue by flapczek** [RushFTK/LiquipediaOsuContributeHelper#8]
after running python staff.py im getting this error:

Traceback (most recent call last):
  File "C:\Users\kamil\Desktop\liquipedia\LiquipediaOsuContributeHelper-main\staff.py", line 58, in <module>
    staffs = read_staffs()
             ^^^^^^^^^^^^^
  File "C:\Users\kamil\Desktop\liquipedia\LiquipediaOsuContributeHelper-main\staff.py", line 15, in read_staffs
    for i in range(3, m_row + 1):
                      ~~~~~~^~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by RushFTK** [comment]
it works for me. but i will try update Staff.xlsx sheet naming so openpyxl will directly read dedicate sheets now.
